// A QR encoder — byte mode, versions 1–14, no dependency.
//
// WHY THIS IS WRITTEN OUT RATHER THAN INSTALLED. Every published encoder either
// drags node-only packages (pngjs, yargs, a graph library) into a renderer
// bundle that has to stay small, or ships a UMD blob with no types. Against
// that, the thing being encoded here is one short `stem://pair?…` URL, and this
// repo already carries the hard part of the work: tests/fixtures/qr-vectors.json
// holds reference symbols generated by macOS CoreImage, module for module,
// including the mask each one chose. An implementation that reproduces those bit
// for bit is verified more thoroughly than a dependency would be, and the
// fixture outlived the PWA that first needed it precisely so this could be
// rebuilt from it.
//
// WHAT IT DELIBERATELY DOES NOT DO. Byte mode only — a URL is bytes, and the
// numeric/alphanumeric modes exist to save space we are not short of. Versions
// stop at 14, whose smallest capacity (140 bytes at level H) is already twice
// the longest pairing link anyone will produce; asking for more throws with a
// sentence rather than silently widening a table nothing tests.
//
// The tables below are the two numbers per (version, level) that ISO/IEC 18004
// does not let you derive: how many error-correction codewords each block
// carries, and how many blocks there are. Everything else — how many codewords a
// symbol holds at all, where the data goes, how long each block is — is computed
// from the geometry, because a derived number cannot be transcribed wrong.

/** The four error-correction levels, weakest to strongest. */
export type QrEcLevel = 'L' | 'M' | 'Q' | 'H';

/** A finished symbol. The quiet zone is the renderer's business, not the encoder's. */
export interface QrSymbol {
  version: number;
  /** Modules per side, `4 * version + 17`. */
  size: number;
  /** Which of the eight masks was applied. */
  mask: number;
  /** Row-major, top row first; true = dark. */
  modules: boolean[][];
}

/** Beyond this the tables stop, and so does the honesty of the tests. */
export const MAX_QR_VERSION = 14;

/** `[error-correction codewords per block, number of blocks]`, versions 1–14. */
const EC_BLOCKS: Record<QrEcLevel, readonly (readonly [number, number])[]> = {
  L: [[7, 1], [10, 1], [15, 1], [20, 1], [26, 1], [18, 2], [20, 2], [24, 2], [30, 2], [18, 4], [20, 4], [24, 4], [26, 4], [30, 4]],
  M: [[10, 1], [16, 1], [26, 1], [18, 2], [24, 2], [16, 4], [18, 4], [22, 4], [22, 5], [26, 5], [30, 5], [22, 8], [22, 9], [24, 9]],
  Q: [[13, 1], [22, 1], [18, 2], [26, 2], [18, 4], [24, 4], [18, 6], [22, 6], [20, 8], [24, 8], [28, 8], [26, 10], [24, 12], [20, 16]],
  H: [[17, 1], [28, 1], [22, 2], [16, 4], [22, 4], [28, 4], [26, 5], [26, 6], [24, 8], [28, 8], [24, 11], [28, 11], [22, 16], [24, 16]]
};

/** Alignment-pattern centre coordinates per version; version 1 has none. */
const ALIGNMENT: readonly (readonly number[])[] = [
  [], [6, 18], [6, 22], [6, 26], [6, 30], [6, 34], [6, 22, 38], [6, 24, 42],
  [6, 26, 46], [6, 28, 50], [6, 30, 54], [6, 32, 58], [6, 34, 62], [6, 26, 46, 66]
];

/** The two-bit encoding of each level in the format information. Not its strength order. */
const EC_BITS: Record<QrEcLevel, number> = { L: 1, M: 0, Q: 3, H: 2 };

// ---------------------------------------------------------------------------
// GF(256), the field the Reed–Solomon parity is computed in.
// ---------------------------------------------------------------------------

const EXP = new Uint8Array(512);
const LOG = new Uint8Array(256);
{
  let x = 1;
  for (let i = 0; i < 255; i++) {
    EXP[i] = x;
    LOG[x] = i;
    x <<= 1;
    if (x & 0x100) x ^= 0x11d; // the primitive polynomial QR fixes
  }
  for (let i = 255; i < 512; i++) EXP[i] = EXP[i - 255];
}

function gfMul(a: number, b: number): number {
  return a === 0 || b === 0 ? 0 : EXP[LOG[a] + LOG[b]];
}

/** The product of `(x - α^i)` for i < degree, highest-degree coefficient first. */
function generatorPoly(degree: number): Uint8Array {
  let poly = Uint8Array.of(1);
  for (let i = 0; i < degree; i++) {
    const next = new Uint8Array(poly.length + 1);
    for (let j = 0; j < poly.length; j++) {
      next[j] ^= poly[j];
      next[j + 1] ^= gfMul(poly[j], EXP[i]);
    }
    poly = next;
  }
  return poly;
}

/** The parity codewords for one block: the remainder of data·x^count mod the generator. */
function parity(data: Uint8Array, count: number): Uint8Array {
  const gen = generatorPoly(count);
  const work = new Uint8Array(data.length + count);
  work.set(data);
  for (let i = 0; i < data.length; i++) {
    const factor = work[i];
    if (factor === 0) continue;
    for (let j = 0; j < gen.length; j++) work[i + j] ^= gfMul(gen[j], factor);
  }
  return work.slice(data.length);
}

// ---------------------------------------------------------------------------
// The function patterns, and with them the symbol's capacity.
// ---------------------------------------------------------------------------

interface Skeleton {
  size: number;
  /** Row-major module colors; only function patterns are set yet. */
  modules: Uint8Array;
  /** 1 where a module belongs to a pattern and cannot carry data. */
  reserved: Uint8Array;
  /** Modules left for data and parity — capacity, before it is divided into codewords. */
  free: number;
}

/**
 * Walk the 15 format-information positions and the dark module. Called twice per
 * symbol: once with `bits` null, to reserve the cells before the data is placed,
 * and once with the real value, after the mask is known.
 *
 * The positions are the standard's, not a rule: the two copies are placed so that
 * a symbol with one corner destroyed still reads.
 */
function walkFormat(sk: Skeleton, bits: number | null): void {
  const { size, modules, reserved } = sk;
  const put = (r: number, c: number, bit: number) => {
    reserved[r * size + c] = 1;
    if (bits !== null) modules[r * size + c] = bit;
  };
  for (let i = 0; i < 15; i++) {
    const bit = bits === null ? 0 : (bits >> i) & 1;
    if (i < 6) put(i, 8, bit);
    else if (i < 8) put(i + 1, 8, bit);
    else put(size - 15 + i, 8, bit);

    if (i < 8) put(8, size - i - 1, bit);
    else if (i === 8) put(8, 7, bit);
    else put(8, 14 - i, bit);
  }
  // The one module that is dark in every symbol ever made.
  reserved[(size - 8) * size + 8] = 1;
  modules[(size - 8) * size + 8] = 1;
}

/** The 18 version bits, in both copies. Versions below 7 carry none. */
function walkVersion(sk: Skeleton, bits: number | null): void {
  const { size, modules, reserved } = sk;
  for (let i = 0; i < 18; i++) {
    const bit = bits === null ? 0 : (bits >> i) & 1;
    const a = Math.floor(i / 3);
    const b = (i % 3) + size - 11;
    reserved[a * size + b] = 1;
    reserved[b * size + a] = 1;
    if (bits !== null) {
      modules[a * size + b] = bit;
      modules[b * size + a] = bit;
    }
  }
}

/** Everything in a symbol that does not depend on the message. */
function skeleton(version: number): Skeleton {
  const size = version * 4 + 17;
  const sk: Skeleton = {
    size,
    modules: new Uint8Array(size * size),
    reserved: new Uint8Array(size * size),
    free: 0
  };
  const set = (r: number, c: number, dark: number) => {
    sk.modules[r * size + c] = dark;
    sk.reserved[r * size + c] = 1;
  };

  // Finders, each with the light separator ring that keeps it from touching data.
  for (const [r0, c0] of [[0, 0], [0, size - 7], [size - 7, 0]]) {
    for (let dr = -1; dr <= 7; dr++) {
      for (let dc = -1; dc <= 7; dc++) {
        const r = r0 + dr;
        const c = c0 + dc;
        if (r < 0 || c < 0 || r >= size || c >= size) continue;
        const inside = dr >= 0 && dr <= 6 && dc >= 0 && dc <= 6;
        const ring = dr === 0 || dr === 6 || dc === 0 || dc === 6;
        const core = dr >= 2 && dr <= 4 && dc >= 2 && dc <= 4;
        set(r, c, inside && (ring || core) ? 1 : 0);
      }
    }
  }

  // Timing: the two alternating lines that tell a decoder how wide a module is.
  for (let i = 8; i < size - 8; i++) {
    set(6, i, i % 2 === 0 ? 1 : 0);
    set(i, 6, i % 2 === 0 ? 1 : 0);
  }

  // Alignment, skipping the three centres that would land on a finder.
  const centres = ALIGNMENT[version - 1];
  for (const r0 of centres) {
    for (const c0 of centres) {
      const nearFinder =
        (r0 <= 8 && c0 <= 8) || (r0 <= 8 && c0 >= size - 9) || (r0 >= size - 9 && c0 <= 8);
      if (nearFinder) continue;
      for (let dr = -2; dr <= 2; dr++) {
        for (let dc = -2; dc <= 2; dc++) {
          set(r0 + dr, c0 + dc, Math.max(Math.abs(dr), Math.abs(dc)) === 1 ? 0 : 1);
        }
      }
    }
  }

  walkFormat(sk, null);
  if (version >= 7) walkVersion(sk, null);

  for (let i = 0; i < sk.reserved.length; i++) if (!sk.reserved[i]) sk.free++;
  return sk;
}

/**
 * How many codewords this version holds in total — counted off the skeleton
 * rather than transcribed, so the one place the standard's tables could be got
 * wrong is the one place they are not consulted. Whatever is left over after the
 * last whole codeword is the remainder bits, which are placed as zeroes.
 */
function totalCodewords(version: number): number {
  return skeleton(version).free >> 3;
}

// ---------------------------------------------------------------------------
// Message → codewords.
// ---------------------------------------------------------------------------

/** Data codewords available at this version and level, once parity is set aside. */
function dataCapacity(version: number, ec: QrEcLevel): number {
  const [ecPerBlock, blocks] = EC_BLOCKS[ec][version - 1];
  return totalCodewords(version) - ecPerBlock * blocks;
}

/** Byte mode counts characters in 8 bits up to version 9, and 16 bits after. */
function countBits(version: number): number {
  return version <= 9 ? 8 : 16;
}

/** The smallest version that fits `length` bytes at this level. */
function chooseVersion(length: number, ec: QrEcLevel): number {
  for (let v = 1; v <= MAX_QR_VERSION; v++) {
    if (4 + countBits(v) + length * 8 <= dataCapacity(v, ec) * 8) return v;
  }
  throw new Error(
    `${length} bytes is more than a QR symbol of version ${MAX_QR_VERSION} carries at level ${ec}`
  );
}

/**
 * The message as codewords: header, bytes, terminator, padding — then split into
 * blocks, parity computed per block, and the whole lot interleaved so that a
 * scratch across the symbol damages every block a little rather than one block
 * fatally. The interleave is the entire point of the block structure.
 */
function codewords(bytes: Uint8Array, version: number, ec: QrEcLevel): Uint8Array {
  const dataCount = dataCapacity(version, ec);
  const bits: number[] = [];
  const push = (value: number, width: number) => {
    for (let i = width - 1; i >= 0; i--) bits.push((value >> i) & 1);
  };

  push(0b0100, 4); // byte mode
  push(bytes.length, countBits(version));
  for (const b of bytes) push(b, 8);
  // Terminator, then out to a whole codeword, then the two pad bytes the standard
  // names, alternating, for as long as there is room.
  for (let i = 0; i < 4 && bits.length < dataCount * 8; i++) bits.push(0);
  while (bits.length % 8 !== 0) bits.push(0);

  const data = new Uint8Array(dataCount);
  for (let i = 0; i < bits.length; i += 8) {
    let byte = 0;
    for (let j = 0; j < 8; j++) byte = (byte << 1) | bits[i + j];
    data[i >> 3] = byte;
  }
  for (let i = bits.length >> 3; i < dataCount; i++) {
    data[i] = (i - (bits.length >> 3)) % 2 === 0 ? 0xec : 0x11;
  }

  // Short blocks first, long blocks after — the order the interleave assumes.
  const [ecPerBlock, blockCount] = EC_BLOCKS[ec][version - 1];
  const shortLen = Math.floor(dataCount / blockCount);
  const longBlocks = dataCount % blockCount;
  const dataBlocks: Uint8Array[] = [];
  const ecBlocks: Uint8Array[] = [];
  let offset = 0;
  for (let b = 0; b < blockCount; b++) {
    const len = shortLen + (b >= blockCount - longBlocks ? 1 : 0);
    const block = data.subarray(offset, offset + len);
    offset += len;
    dataBlocks.push(block);
    ecBlocks.push(parity(block, ecPerBlock));
  }

  const out = new Uint8Array(dataCount + ecPerBlock * blockCount);
  let at = 0;
  for (let i = 0; i <= shortLen; i++) {
    for (const block of dataBlocks) if (i < block.length) out[at++] = block[i];
  }
  for (let i = 0; i < ecPerBlock; i++) {
    for (const block of ecBlocks) out[at++] = block[i];
  }
  return out;
}

// ---------------------------------------------------------------------------
// Masking, and the score that chooses between the eight of them.
// ---------------------------------------------------------------------------

function maskAt(pattern: number, r: number, c: number): boolean {
  switch (pattern) {
    case 0: return (r + c) % 2 === 0;
    case 1: return r % 2 === 0;
    case 2: return c % 3 === 0;
    case 3: return (r + c) % 3 === 0;
    case 4: return (Math.floor(r / 2) + Math.floor(c / 3)) % 2 === 0;
    case 5: return ((r * c) % 2) + ((r * c) % 3) === 0;
    case 6: return (((r * c) % 2) + ((r * c) % 3)) % 2 === 0;
    default: return (((r * c) % 3) + ((r + c) % 2)) % 2 === 0;
  }
}

/** BCH(15,5) for the format bits, and BCH(18,6) for the version bits. */
function bch(data: number, generator: number, width: number): number {
  const digit = (n: number) => (n === 0 ? 0 : 32 - Math.clz32(n));
  let rest = data << width;
  while (digit(rest) - digit(generator) >= 0) rest ^= generator << (digit(rest) - digit(generator));
  return ((data << width) | rest) >>> 0;
}

/**
 * The four penalty rules, in the standard's own units: long same-colour runs,
 * solid 2×2 blocks, anything that reads like a finder pattern, and an overall
 * light/dark imbalance. Lowest total wins.
 */
function penalty(modules: boolean[][], size: number): number {
  let score = 0;
  let dark = 0;

  const FINDER = [true, false, true, true, true, false, true, false, false, false, false];
  const looksLikeFinder = (line: boolean[], at: number): boolean => {
    for (let i = 0; i < 11; i++) if (line[at + i] !== FINDER[i]) return false;
    return true;
  };

  for (let pass = 0; pass < 2; pass++) {
    for (let a = 0; a < size; a++) {
      const line: boolean[] = [];
      for (let b = 0; b < size; b++) line.push(pass === 0 ? modules[a][b] : modules[b][a]);
      // Rule 1: five in a row is 3, each further one is 1 more.
      let run = 1;
      for (let b = 1; b < size; b++) {
        if (line[b] === line[b - 1]) run++;
        else {
          if (run >= 5) score += 3 + (run - 5);
          run = 1;
        }
      }
      if (run >= 5) score += 3 + (run - 5);
      // Rule 3: the 1:1:3:1:1 finder proportion, with its four-module light run
      // on either side. Both orientations of the sequence count.
      for (let b = 0; b + 11 <= size; b++) {
        if (looksLikeFinder(line, b)) score += 40;
        const reversed = line.slice(b, b + 11).reverse();
        if (looksLikeFinder(reversed, 0)) score += 40;
      }
    }
  }

  for (let r = 0; r + 1 < size; r++) {
    for (let c = 0; c + 1 < size; c++) {
      const v = modules[r][c];
      // Rule 2: every solid 2×2 block, counted where its top-left corner is.
      if (v === modules[r][c + 1] && v === modules[r + 1][c] && v === modules[r + 1][c + 1]) {
        score += 3;
      }
    }
  }

  for (let r = 0; r < size; r++) for (let c = 0; c < size; c++) if (modules[r][c]) dark++;
  // Rule 4: ten points per 5% the symbol strays from half dark.
  score += Math.floor(Math.abs((dark * 100) / (size * size) - 50) / 5) * 10;
  return score;
}

/** Lay the codewords into a skeleton under one mask, and stamp the format bits. */
function render(version: number, ec: QrEcLevel, payload: Uint8Array, mask: number): boolean[][] {
  const sk = skeleton(version);
  const { size, modules, reserved } = sk;

  // Two columns at a time, right to left, alternating up and down — skipping the
  // vertical timing line, which is not a column of data at all.
  let bit = 0;
  let upward = true;
  for (let right = size - 1; right > 0; right -= 2) {
    if (right === 6) right--;
    for (let step = 0; step < size; step++) {
      const r = upward ? size - 1 - step : step;
      for (const c of [right, right - 1]) {
        if (reserved[r * size + c]) continue;
        const byte = bit >> 3;
        let dark = byte < payload.length && ((payload[byte] >> (7 - (bit & 7))) & 1) === 1;
        bit++;
        if (maskAt(mask, r, c)) dark = !dark;
        modules[r * size + c] = dark ? 1 : 0;
      }
    }
    upward = !upward;
  }

  walkFormat(sk, bch((EC_BITS[ec] << 3) | mask, 0b101_0011_0111, 10) ^ 0b101_0100_0001_0010);
  if (version >= 7) walkVersion(sk, bch(version, 0b1_1111_0010_0101, 12));

  const grid: boolean[][] = [];
  for (let r = 0; r < size; r++) {
    const row: boolean[] = [];
    for (let c = 0; c < size; c++) row.push(modules[r * size + c] === 1);
    grid.push(row);
  }
  return grid;
}

/**
 * Encode `text` as a QR symbol.
 *
 * `mask` forces one of the eight patterns instead of scoring them, which exists
 * for the conformance test: a reference symbol built by some other encoder is
 * only comparable module-for-module once both agree which mask was used, and
 * mask choice is the one part of the standard that is advisory.
 */
export function encodeQr(
  text: string,
  { ecLevel = 'M', mask }: { ecLevel?: QrEcLevel; mask?: number } = {}
): QrSymbol {
  const bytes = new TextEncoder().encode(text);
  const version = chooseVersion(bytes.length, ecLevel);
  const payload = codewords(bytes, version, ecLevel);
  const size = version * 4 + 17;

  if (mask !== undefined) {
    return { version, size, mask, modules: render(version, ecLevel, payload, mask) };
  }
  let best: QrSymbol | null = null;
  let bestScore = Infinity;
  for (let m = 0; m < 8; m++) {
    const modules = render(version, ecLevel, payload, m);
    const score = penalty(modules, size);
    if (score < bestScore) {
      bestScore = score;
      best = { version, size, mask: m, modules };
    }
  }
  return best!;
}

/**
 * The dark modules as one SVG path, in a coordinate system of one unit per
 * module with `quiet` units of margin. One path rather than a rect per module:
 * a version-6 symbol is 1,700 modules, and half of them as separate elements is
 * a lot of DOM for a picture of a square.
 *
 * The quiet zone is not decoration — a scanner needs the light border to find the
 * symbol's edge — so it is part of the geometry here rather than left to CSS
 * padding that a later layout change could quietly remove.
 */
export function qrPath(symbol: QrSymbol, quiet = 4): { d: string; extent: number } {
  const parts: string[] = [];
  for (let r = 0; r < symbol.size; r++) {
    for (let c = 0; c < symbol.size; c++) {
      if (symbol.modules[r][c]) parts.push(`M${c + quiet} ${r + quiet}h1v1h-1z`);
    }
  }
  return { d: parts.join(''), extent: symbol.size + quiet * 2 };
}

/**
 * The same path, or null when there is no symbol to draw.
 *
 * encodeQr throws on text past version 14 — deliberately, since a caller that
 * knows what it is encoding wants to hear about a payload that outgrew the
 * format. A UI is not that caller. The pairing dialog encodes a link built from
 * an address the user chose, and a long one (a tunnel hostname, a proxied path)
 * takes the throw straight through a renderer with no error boundary, blanking
 * the whole Settings window over a picture. Nothing about a QR code is worth a
 * white window: the code and the address beside it are the fallback the dialog
 * already shows to anyone whose camera cannot help them.
 *
 * Every failure is treated the same way for the same reason — a bug in here
 * should cost the plate, not the surface it sits on.
 */
export function tryQrPath(
  text: string,
  opts: { ecLevel?: QrEcLevel; quiet?: number } = {}
): { d: string; extent: number } | null {
  try {
    return qrPath(encodeQr(text, { ecLevel: opts.ecLevel }), opts.quiet);
  } catch {
    return null;
  }
}
