import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { encodeQr, qrPath, MAX_QR_VERSION, type QrEcLevel } from '../../src/shared/qr';

// The QR encoder against symbols nobody here produced.
//
// tests/fixtures/qr-vectors.json holds reference symbols generated by macOS
// CoreImage — module for module, quiet zone stripped, with the mask each one
// chose. Comparing against another implementation's output is the only test that
// means anything for an encoder: a self-consistent one that gets the padding or
// the interleave wrong still looks like a QR code, and still scans as nothing.
//
// Each vector is checked twice. Forced to CoreImage's mask, the whole matrix must
// match, which pins the encoding, the parity, the interleave and the placement.
// Then, where the fixture says CoreImage's mask was also the one the penalty
// rules pick (`autoMask`), the unforced call must arrive there by itself — mask
// choice is advisory in the standard, so this is asserted only where the two
// implementations are known to agree.

interface Vector {
  text: string;
  ecLevel: QrEcLevel;
  version: number;
  mask: number;
  autoMask: boolean;
  rows: string[];
}

const vectors: Vector[] = JSON.parse(
  readFileSync(new URL('../fixtures/qr-vectors.json', import.meta.url), 'utf8')
).vectors;

function asRows(modules: boolean[][]): string[] {
  return modules.map((row) => row.map((dark) => (dark ? '1' : '0')).join(''));
}

describe('QR encoder', () => {
  it('has vectors to check against', () => {
    expect(vectors.length).toBeGreaterThan(8);
  });

  for (const v of vectors) {
    const name = `${JSON.stringify(v.text.slice(0, 32))}… level ${v.ecLevel}`;

    it(`reproduces ${name} under CoreImage's mask`, () => {
      const symbol = encodeQr(v.text, { ecLevel: v.ecLevel, mask: v.mask });
      expect(symbol.version).toBe(v.version);
      expect(symbol.size).toBe(v.rows.length);
      expect(asRows(symbol.modules)).toEqual(v.rows);
    });

    if (v.autoMask) {
      it(`picks mask ${v.mask} for ${name} on its own`, () => {
        const symbol = encodeQr(v.text, { ecLevel: v.ecLevel });
        expect(symbol.mask).toBe(v.mask);
        expect(asRows(symbol.modules)).toEqual(v.rows);
      });
    }
  }
});

describe('QR sizing', () => {
  it('grows only as far as the message needs', () => {
    // Version 1 at level M carries 14 bytes; the fifteenth costs a version.
    expect(encodeQr('x'.repeat(14), { ecLevel: 'M' }).version).toBe(1);
    expect(encodeQr('x'.repeat(15), { ecLevel: 'M' }).version).toBe(2);
  });

  it('counts a multi-byte character as its UTF-8 bytes', () => {
    // Three bytes each, so five of them are one byte past a version-1 M symbol.
    expect(encodeQr('☃'.repeat(4), { ecLevel: 'M' }).version).toBe(1);
    expect(encodeQr('☃'.repeat(5), { ecLevel: 'M' }).version).toBe(2);
  });

  it('crosses the 16-bit character count without losing a byte', () => {
    // Versions 10 and up count characters in 16 bits rather than 8. A symbol that
    // silently truncated the count would still encode, and still scan short.
    const text = 'y'.repeat(300);
    const symbol = encodeQr(text, { ecLevel: 'M' });
    expect(symbol.version).toBeGreaterThanOrEqual(10);
    expect(symbol.size).toBe(symbol.version * 4 + 17);
  });

  it('says so rather than truncating when a message is too long', () => {
    expect(() => encodeQr('z'.repeat(5000), { ecLevel: 'H' })).toThrow(
      new RegExp(`version ${MAX_QR_VERSION}`)
    );
  });
});

describe('qrPath', () => {
  it('surrounds the symbol with the quiet zone a scanner needs', () => {
    const symbol = encodeQr('Stem', { ecLevel: 'M' });
    const { d, extent } = qrPath(symbol, 4);
    expect(extent).toBe(symbol.size + 8);
    // The top-left finder's outermost dark module sits at the quiet zone's edge.
    expect(d.startsWith('M4 4h1v1h-1z')).toBe(true);
  });

  it('draws one subpath per dark module and nothing else', () => {
    const symbol = encodeQr('Stem', { ecLevel: 'M' });
    const dark = symbol.modules.flat().filter(Boolean).length;
    expect(qrPath(symbol).d.split('M').length - 1).toBe(dark);
  });
});
